### PR TITLE
Make emails optional for new registration

### PR DESCRIPTION
**Pull request by oohwooh**
Could possibly have unintended side effects, will need to take a closer look.

### CODE REVIEW

**Comment by DragonBallZeke** [comment]
In `Clear/app/Services/Registration.php` email is set to `null` by default, so I figured that would be covered by the case. I'll add that trim statement in, thanks!

**Comment by DragonBallZeke** [comment]
Looks like it would probably be fine, can you confirm?

**Comment by tylermenezes** [comment]
I _think_ that should be fine, but if you want to add an `if (!$email) return null` it's not a terrible idea. Otherwise if someone bans a null email it will ban lots of people.

**Comment by tylermenezes** [comment]
You're missing a semicolon this won't actually work ;D

**Pull request closed without merging**
